-- SQL schema definition executed at container start
\connect db;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TYPE bike_infra_type AS ENUM (
    'track', 
    'lane', 
    'footway', 
    'share_busway', 
    'share_lane', 
    'none'
);

CREATE TABLE IF NOT EXISTS network_segments (
    -- primary key generated automatically from sequence
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- segment data
    osm_id TEXT UNIQUE,
    street_name TEXT,
    geom GEOMETRY(LineString, 4326) NOT NULL,

    -- ENUMs for faster filtering
    bike_infra bike_infra_type NOT NULL DEFAULT 'none',
    
    -- numerical parameters
    maxspeed SMALLINT CHECK (maxspeed > 0),

    --booleans
    is_oneway BOOLEAN DEFAULT FALSE,
    is_lit BOOLEAN DEFAULT FALSE,

    -- parameters too varied to be other than TEXT
    surface TEXT,
    highway TEXT
);

-- index for quick data query (GIST index)
CREATE INDEX IF NOT EXISTS idx_network_segments_geom
    ON network_segments
    USING GIST (geom);

CREATE TABLE IF NOT EXISTS segment_metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    segment_id INTEGER NOT NULL
        REFERENCES network_segments(id),
    
    -- metrics info
    metric_name TEXT NOT NULL,
    metric_version TEXT NOT NULL,
    
    -- metric score for given segment
    total_score NUMERIC(5,4) CHECK (total_score >= 0 AND total_score <= 1),

    -- scores of features of the given metric are stored in JSON format
    metric_features_scores JSONB NOT NULL,
    -- weights used are stored in JSON format
    metadata JSONB,

    UNIQUE (segment_id, metric_name, metric_version)
);